perl -pi -e 's/%APP_ENV%/$APP_ENV/g' '.env'
perl -pi -e 's/%DB_HOST%/$DB_HOST/g' '.env'
perl -pi -e 's/%DB_DATABASE%/$DB_DATABASE/g' '.env'
perl -pi -e 's/%DB_USERNAME%/$DB_USERNAME/g' '.env'
perl -pi -e 's/%DB_USERNAME%/$DB_USERNAME/g' '.env'